"""
Django settings for misfinanzas project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from dotenv import load_dotenv
from pathlib import Path
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env for local development (non-production)
env_path = BASE_DIR.parent / '.env'
if env_path.exists():
    load_dotenv(dotenv_path=env_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-+^p_y(@#%!(*c-n0=z&e2hl+2pu3f23gr4s01i)7bn70=da-(*')

# SECURITY WARNING: don't run with debug turned on in production!
# In production (when USE_POSTGRES=True), DEBUG defaults to False
# In local development (SQLite), DEBUG defaults to True
USE_POSTGRES = os.environ.get('USE_POSTGRES', 'False') == 'True'
DEBUG = os.environ.get('DEBUG', str(not USE_POSTGRES)) == 'True'

ALLOWED_HOSTS = ['*']

# CSRF trusted origins for Railway deployment
CSRF_TRUSTED_ORIGINS = [
    'https://cachinapp.com',
    'https://*.railway.app',
    'https://*.up.railway.app',
]

# Application definition

INSTALLED_APPS = [
    "expenses.apps.ExpensesConfig",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'misfinanzas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'misfinanzas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Use PostgreSQL in production (Railway) and SQLite in local development
if USE_POSTGRES:
    # PostgreSQL configuration for Railway
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('PGDATABASE'),
            'USER': os.environ.get('PGUSER'),
            'PASSWORD': os.environ.get('PGPASSWORD'),
            'HOST': os.environ.get('PGHOST'),
            'PORT': os.environ.get('PGPORT', '5432'),
        }
    }
else:
    # SQLite configuration for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] if os.path.exists(os.path.join(BASE_DIR, 'static')) else []

# Redirects and email backend for auth flows (development)
# After login, go to user profile page
LOGIN_REDIRECT_URL = '/user/'
LOGOUT_REDIRECT_URL = '/'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email fetch settings (IMAP)
EMAIL_FETCH_IMAP_HOST = os.environ.get('EMAIL_FETCH_IMAP_HOST', 'imap.cachinapp.com')
EMAIL_FETCH_IMAP_PORT = int(os.environ.get('EMAIL_FETCH_IMAP_PORT', '993'))
EMAIL_FETCH_IMAP_SSL = os.environ.get('EMAIL_FETCH_IMAP_SSL', 'True') == 'True'
EMAIL_FETCH_USER = os.environ.get('EMAIL_FETCH_USER')  # optional shared mailbox user
EMAIL_FETCH_PASS = os.environ.get('EMAIL_FETCH_PASS')  # optional shared mailbox password

# Celery / Celery Beat
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/1')
CELERY_TIMEZONE = os.environ.get('CELERY_TIMEZONE', TIME_ZONE)
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'False') == 'True'
CELERY_BEAT_SCHEDULE = {
    'fetch-emails-daily': {
        'task': 'expenses.tasks.fetch_emails_task',
        'schedule': crontab(hour=4, minute=0),  # 04:00 UTC daily
    },
}
