# Generated by Django 4.2.27 on 2025-12-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_cleanup_polls_tables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
