# Generated by Django 4.2.27 on 2025-12-14 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0005_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_localpart', models.CharField(max_length=64, unique=True)),
                ('domain', models.CharField(default='cachinapp.com', max_length=255)),
                ('full_address', models.EmailField(max_length=254, unique=True)),
                ('mailbox_username', models.CharField(blank=True, max_length=255)),
                ('mailbox_password', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Email Config',
                'verbose_name_plural': 'User Email Configs',
            },
        ),
        migrations.CreateModel(
            name='UserEmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('from_address', models.CharField(blank=True, max_length=500)),
                ('to_addresses', models.TextField(blank=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('raw_eml', models.BinaryField()),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-downloaded_at'],
                'unique_together': {('user', 'message_id')},
            },
        ),
    ]
