# Generated by Django 4.2.27 on 2025-12-17 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0007_transaction_external_pending'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='SplitwiseAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(blank=True, max_length=255, null=True)),
                ('oauth_token_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('splitwise_user_id', models.CharField(blank=True, max_length=64, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='splitwise', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
