# Generated by Django 4.2.27 on 2025-12-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_transaction_unique_together_splitwiseaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(db_index=True, max_length=3, unique=True)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['currency'],
            },
        ),
    ]
