# Generated by Django 4.2.27 on 2025-12-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_defaultexchangerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pre-calculated USD amount for performance', max_digits=14, null=True),
        ),
        migrations.AddIndex(
            model_name='exchange',
            index=models.Index(fields=['user', 'source_currency', 'target_currency', 'date'], name='ex_user_src_tgt_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date', 'id'], name='tx_user_date_id'),
        ),
    ]
