# Generated by Django 4.2.27 on 2025-12-18 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0010_add_amount_usd_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_tokens', models.CharField(help_text='Space-separated tokens from transaction description', max_length=500)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Specific amount if part of the rule', max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, help_text='Currency code (e.g., USD, UYU)', max_length=3, null=True)),
                ('usage_count', models.IntegerField(default=0, help_text='Times this rule has been used')),
                ('accuracy', models.FloatField(default=1.0, help_text='Accuracy score (0-1) based on matching transactions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.category')),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.payee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usage_count', '-created_at'],
                'indexes': [models.Index(fields=['user', 'description_tokens'], name='rule_user_tokens'), models.Index(fields=['user', 'created_at'], name='rule_user_created')],
            },
        ),
    ]
