# Generated by Django 4.2.27 on 2025-12-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_add_categorization_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailconfig',
            name='forwarding_email',
            field=models.EmailField(blank=True, help_text='Personal email address used when forwarding invoices', max_length=254, null=True, unique=True),
        ),
    ]
