# Generated by Django 4.2.27 on 2025-12-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_update_existing_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailconfig',
            name='user_email',
            field=models.EmailField(blank=True, help_text='Email personal desde el cual reenviarás correos', max_length=254),
        ),
    ]
