# Generated by Django 4.2.27 on 2025-12-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_userpreferences'),
        ('expenses', '0014_useremailconfig_user_email'),
    ]

    operations = [
    ]
