# Generated by Django 4.2.27 on 2025-12-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_merge_20251222_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailconfig',
            name='forwarding_confirmed',
            field=models.BooleanField(default=False, help_text='Si se confirmó el reenvío automático de Gmail'),
        ),
        migrations.AddField(
            model_name='useremailconfig',
            name='forwarding_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora cuando se confirmó el forwarding', null=True),
        ),
    ]
