# Generated by Django 4.2.27 on 2025-12-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_useremailconfig_forwarding_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailmessage',
            name='gmail_confirmation_link',
            field=models.URLField(blank=True, help_text='Gmail forwarding confirmation link for user to click', max_length=1000, null=True),
        ),
    ]
