# Generated by Django 4.2.27 on 2025-12-26 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0017_useremailmessage_gmail_confirmation_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symbol', models.CharField(help_text='Stock ticker symbol', max_length=20)),
                ('bought', models.BooleanField(help_text='True for buy, False for sell')),
                ('amount', models.DecimalField(decimal_places=6, help_text='Number of shares', max_digits=14)),
                ('unitprice', models.DecimalField(decimal_places=4, help_text='Price per share in USD', max_digits=14)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('transaction', models.ForeignKey(blank=True, help_text='Corresponding cash transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['user', 'date', 'id'], name='stock_user_date_id'), models.Index(fields=['user', 'symbol'], name='stock_user_symbol')],
            },
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='transaction_images/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('raw_ocr_text', models.TextField(blank=True, help_text='Raw OCR text extracted')),
                ('confidence_score', models.FloatField(blank=True, help_text='Overall confidence 0-1', null=True)),
                ('extracted_data', models.JSONField(blank=True, help_text='Parsed transaction data from LlamaCloud', null=True)),
                ('session_id', models.CharField(db_index=True, help_text='UUID to group multiple images uploaded together', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'session_id', 'status'], name='img_user_session_status'), models.Index(fields=['user', 'uploaded_at'], name='img_user_uploaded')],
            },
        ),
    ]
