# Generated by Django 4.2.27 on 2025-12-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0018_stock_imageupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='image',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='image_path',
            field=models.CharField(default='', help_text='Temporary file path', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageupload',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
