# Generated by Django 4.2.27 on 2025-12-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_remove_imageupload_image_imageupload_image_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image_path',
            field=models.CharField(blank=True, help_text='Temporary file path (legacy)', max_length=500, null=True),
        ),
    ]
