# Generated by Django 4.2.27 on 2026-03-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0020_imageupload_image_alter_imageupload_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='is_credit_card',
            field=models.BooleanField(default=False),
        ),
    ]
