# Generated by Django 4.2.27 on 2026-03-17 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0022_add_budget_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceBankMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(max_length=50)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mapeo banco-fuente',
                'verbose_name_plural': 'mapeos banco-fuente',
                'unique_together': {('user', 'bank_code', 'currency')},
            },
        ),
    ]
