# Generated by Django 4.2.27 on 2026-04-19 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0025_transaction_is_reimbursable'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_virtual',
            field=models.BooleanField(default=False, help_text='Virtual counter-leg of a trade (e.g., shares received or IBKR deposit). Not a real cash flow.'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paired_transaction',
            field=models.ForeignKey(blank=True, help_text='The other leg of a paired trade or transfer transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pair', to='expenses.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(max_length=20),
        ),
    ]
